sonar.projectKey=wallet-transfer-assignment
sonar.projectName=wallet-transfer-assignment
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/.git/**,**/.github/**,**/vendor/**,**/coverage/**,**/*_test.go

# Produced by: go test ./... -coverprofile=coverage.out
sonar.go.coverage.reportPaths=coverage.out
